### ISSUE TITLE
import_testssl.sh_csv_to_ES.py

### ISSUE THREAD

**Issue by KraT0s10k2** [TKCERT/testssl.sh-masscan#6]
Hello, i've a problem with import_testssl.sh_csv_to_ES.py: 

./import_testssl.sh_csv_to_ES.py *.csv
Traceback (most recent call last):
  File "./import_testssl.sh_csv_to_ES.py", line 5, in <module>
    from docTestssl import DocTestSSLResult
  File "/test/testssl-scan/docTestssl.py", line 4, in <module>
    from elasticsearch_dsl import DocType, Object, Date, String, Integer, Short, Boolean
ImportError: cannot import name 'String'

Python 3.6.4
and all dependencies installed

Any idea?

Thanks for ur work

**Comment by Turtle-Sec** [comment]
I have the same problem, did you manage to solve it?

**Comment by Turtle-Sec** [comment]
Hi guys ! 
The index types changed in elasticsearch 5.0. The string type has been replaced by the text (analyzed) and keyword (not analyzed) types. You're specifying the text type, but keyword is what you want for no analysis.
So change String to Text or Keyword. Moreover, you're remove the parenthesis content. Example :grinning: "signalgo": Keyword(fields={'raw': Keyword((index='not_analyzed'))}),

->  "signalgo": Keyword(fields={'raw': Keyword()}),
